### ISSUE TITLE
W10 1803 17763.107

### ISSUE THREAD

**Issue by azertyqsdf956** [SambaEdu/se3-docs#13]
Bonjour,

A titre informatif seulement. (désolé si j'ai pas ouvert l'issue au bon endroit)

Un collègue m'a informé qu'en septembre 2018 Windows a lancé un correctif j'ai testé d'intégrer une W10 1803 d'octobre 2018 sur un SE3 et cela a fonctionné.

J'ai intégré une W10 1803 avec l'iso d'octobre 2018

![image](https://user-images.githubusercontent.com/45298773/51353402-d57fce80-1ab0-11e9-95a6-6d432070a8f4.png)

Et effectivement cela a marché

![image](https://user-images.githubusercontent.com/45298773/51353418-e4668100-1ab0-11e9-87a4-748434e31702.png)

Sur PowerShell j'ai tapé Get-SmbServerConfiguration :

![image](https://user-images.githubusercontent.com/45298773/51353444-f3e5ca00-1ab0-11e9-8865-336dcb247aee.png)

Cordialement.

**Comment by mbansse** [comment]
Bonjour. A priori mieux vaut ne pas s'embêter avec la version 1803. La version 1809 fonctionne nativement et sans patchs ou autres modifications inhabituelle. Il faut donc mieux télécharger l'iso 1809, et mettre en place l'installation automatique.

**Comment by azertyqsdf956** [comment]
Erreur de ma part c'est la 1809 et en plus c'est écrit sur le screen. L'iso d'octobre 2018 dont je parle est la version 1809.
